define(function(){
  var brandData = [
  {
    "letter": "a",
    "data": [{
      "text": "阿斯顿·马丁",
      "img": "http://x.autoimg.cn/m/news/brand/35.jpg",
      "brandId": "35"
    }, {
      "text": "安凯客车",
      "img": "http://x.autoimg.cn/m/news/brand/221.jpg",
      "brandId": "221"
    }, {
      "text": "奥迪",
      "img": "http://x.autoimg.cn/m/news/brand/33.jpg",
      "brandId": "33"
    }, {
      "text": "ALPINA",
      "img": "http://x.autoimg.cn/m/news/brand/276.jpg",
      "brandId": "276"
    }]
  }, {
    "letter": "b",
    "data": [{
      "text": "巴博斯",
      "img": "http://x.autoimg.cn/m/news/brand/140.jpg",
      "brandId": "140"
    }, {
      "text": "宝骏",
      "img": "http://x.autoimg.cn/m/news/brand/120.jpg",
      "brandId": "120"
    }, {
      "text": "宝马",
      "img": "http://x.autoimg.cn/m/news/brand/15.jpg",
      "brandId": "15"
    }, {
      "text": "宝沃",
      "img": "http://x.autoimg.cn/m/news/brand/231.jpg",
      "brandId": "231"
    }, {
      "text": "保时捷",
      "img": "http://x.autoimg.cn/m/news/brand/40.jpg",
      "brandId": "40"
    }, {
      "text": "北京",
      "img": "http://x.autoimg.cn/m/news/brand/27.jpg",
      "brandId": "27"
    }, {
      "text": "北汽幻速",
      "img": "http://x.autoimg.cn/m/news/brand/203.jpg",
      "brandId": "203"
    }, {
      "text": "北汽绅宝",
      "img": "http://x.autoimg.cn/m/news/brand/173.jpg",
      "brandId": "173"
    }, {
      "text": "北汽威旺",
      "img": "http://x.autoimg.cn/m/news/brand/143.jpg",
      "brandId": "143"
    }, {
      "text": "北汽新能源",
      "img": "http://x.autoimg.cn/m/news/brand/208.jpg",
      "brandId": "208"
    }, {
      "text": "北汽制造",
      "img": "http://x.autoimg.cn/m/news/brand/154.jpg",
      "brandId": "154"
    }, {
      "text": "奔驰",
      "img": "http://x.autoimg.cn/m/news/brand/36.jpg",
      "brandId": "36"
    }, {
      "text": "奔腾",
      "img": "http://x.autoimg.cn/m/news/brand/95.jpg",
      "brandId": "95"
    }, {
      "text": "本田",
      "img": "http://x.autoimg.cn/m/news/brand/14.jpg",
      "brandId": "14"
    }, {
      "text": "比亚迪",
      "img": "http://x.autoimg.cn/m/news/brand/75.jpg",
      "brandId": "75"
    }, {
      "text": "标致",
      "img": "http://x.autoimg.cn/m/news/brand/13.jpg",
      "brandId": "13"
    }, {
      "text": "别克",
      "img": "http://x.autoimg.cn/m/news/brand/38.jpg",
      "brandId": "38"
    }, {
      "text": "宾利",
      "img": "http://x.autoimg.cn/m/news/brand/39.jpg",
      "brandId": "39"
    }, {
      "text": "布加迪",
      "img": "http://x.autoimg.cn/m/news/brand/37.jpg",
      "brandId": "37"
    }]
  }, {
    "letter": "c",
    "data": [{
      "text": "昌河",
      "img": "http://x.autoimg.cn/m/news/brand/79.jpg",
      "brandId": "79"
    }, {
      "text": "成功汽车",
      "img": "http://x.autoimg.cn/m/news/brand/196.jpg",
      "brandId": "196"
    }]
  }, {
    "letter": "d",
    "data": [{
      "text": "大众",
      "img": "http://x.autoimg.cn/m/news/brand/1.jpg",
      "brandId": "1"
    }, {
      "text": "道奇",
      "img": "http://x.autoimg.cn/m/news/brand/41.jpg",
      "brandId": "41"
    }, {
      "text": "东风",
      "img": "http://x.autoimg.cn/m/news/brand/32.jpg",
      "brandId": "32"
    }, {
      "text": "东风风度",
      "img": "http://x.autoimg.cn/m/news/brand/187.jpg",
      "brandId": "187"
    }, {
      "text": "东风风光",
      "img": "http://x.autoimg.cn/m/news/brand/259.jpg",
      "brandId": "259"
    }, {
      "text": "东风风神",
      "img": "http://x.autoimg.cn/m/news/brand/113.jpg",
      "brandId": "113"
    }, {
      "text": "东风风行",
      "img": "http://x.autoimg.cn/m/news/brand/165.jpg",
      "brandId": "165"
    }, {
      "text": "东风小康",
      "img": "http://x.autoimg.cn/m/news/brand/142.jpg",
      "brandId": "142"
    }, {
      "text": "东南",
      "img": "http://x.autoimg.cn/m/news/brand/81.jpg",
      "brandId": "81"
    }, {
      "text": "DS",
      "img": "http://x.autoimg.cn/m/news/brand/169.jpg",
      "brandId": "169"
    }]
  }, {
    "letter": "f",
    "data": [{
      "text": "法拉利",
      "img": "http://x.autoimg.cn/m/news/brand/42.jpg",
      "brandId": "42"
    }, {
      "text": "菲亚特",
      "img": "http://x.autoimg.cn/m/news/brand/11.jpg",
      "brandId": "11"
    }, {
      "text": "丰田",
      "img": "http://x.autoimg.cn/m/news/brand/3.jpg",
      "brandId": "3"
    }, {
      "text": "福迪",
      "img": "http://x.autoimg.cn/m/news/brand/141.jpg",
      "brandId": "141"
    }, {
      "text": "福汽启腾",
      "img": "http://x.autoimg.cn/m/news/brand/197.jpg",
      "brandId": "197"
    }, {
      "text": "福特",
      "img": "http://x.autoimg.cn/m/news/brand/8.jpg",
      "brandId": "8"
    }, {
      "text": "福田",
      "img": "http://x.autoimg.cn/m/news/brand/96.jpg",
      "brandId": "96"
    }]
  }, {
    "letter": "g",
    "data": [{
      "text": "观致",
      "img": "http://x.autoimg.cn/m/news/brand/152.jpg",
      "brandId": "152"
    }, {
      "text": "光冈",
      "img": "http://x.autoimg.cn/m/news/brand/116.jpg",
      "brandId": "116"
    }, {
      "text": "广汽传祺",
      "img": "http://x.autoimg.cn/m/news/brand/82.jpg",
      "brandId": "82"
    }, {
      "text": "广汽吉奥",
      "img": "http://x.autoimg.cn/m/news/brand/108.jpg",
      "brandId": "108"
    }, {
      "text": "GMC",
      "img": "http://x.autoimg.cn/m/news/brand/112.jpg",
      "brandId": "112"
    }]
  }, {
    "letter": "h",
    "data": [{
      "text": "哈飞",
      "img": "http://x.autoimg.cn/m/news/brand/24.jpg",
      "brandId": "24"
    }, {
      "text": "哈弗",
      "img": "http://x.autoimg.cn/m/news/brand/181.jpg",
      "brandId": "181"
    }, {
      "text": "海格",
      "img": "http://x.autoimg.cn/m/news/brand/150.jpg",
      "brandId": "150"
    }, {
      "text": "海马",
      "img": "http://x.autoimg.cn/m/news/brand/86.jpg",
      "brandId": "86"
    }, {
      "text": "汉腾汽车",
      "img": "http://x.autoimg.cn/m/news/brand/267.jpg",
      "brandId": "267"
    }, {
      "text": "悍马",
      "img": "http://x.autoimg.cn/m/news/brand/43.jpg",
      "brandId": "43"
    }, {
      "text": "恒天",
      "img": "http://x.autoimg.cn/m/news/brand/164.jpg",
      "brandId": "164"
    }, {
      "text": "红旗",
      "img": "http://x.autoimg.cn/m/news/brand/91.jpg",
      "brandId": "91"
    }, {
      "text": "华凯",
      "img": "http://x.autoimg.cn/m/news/brand/245.jpg",
      "brandId": "245"
    }, {
      "text": "华利",
      "img": "http://x.autoimg.cn/m/news/brand/237.jpg",
      "brandId": "237"
    }, {
      "text": "华普",
      "img": "http://x.autoimg.cn/m/news/brand/85.jpg",
      "brandId": "85"
    }, {
      "text": "华颂",
      "img": "http://x.autoimg.cn/m/news/brand/220.jpg",
      "brandId": "220"
    }, {
      "text": "华泰",
      "img": "http://x.autoimg.cn/m/news/brand/87.jpg",
      "brandId": "87"
    }, {
      "text": "华泰新能源",
      "img": "http://x.autoimg.cn/m/news/brand/260.jpg",
      "brandId": "260"
    }, {
      "text": "黄海",
      "img": "http://x.autoimg.cn/m/news/brand/97.jpg",
      "brandId": "97"
    }]
  }, {
    "letter": "j",
    "data": [{
      "text": "吉利汽车",
      "img": "http://x.autoimg.cn/m/news/brand/25.jpg",
      "brandId": "25"
    }, {
      "text": "江淮",
      "img": "http://x.autoimg.cn/m/news/brand/84.jpg",
      "brandId": "84"
    }, {
      "text": "江铃",
      "img": "http://x.autoimg.cn/m/news/brand/119.jpg",
      "brandId": "119"
    }, {
      "text": "江铃集团轻汽",
      "img": "http://x.autoimg.cn/m/news/brand/210.jpg",
      "brandId": "210"
    }, {
      "text": "江铃集团新能源",
      "img": "http://x.autoimg.cn/m/news/brand/270.jpg",
      "brandId": "270"
    }, {
      "text": "捷豹",
      "img": "http://x.autoimg.cn/m/news/brand/44.jpg",
      "brandId": "44"
    }, {
      "text": "金杯",
      "img": "http://x.autoimg.cn/m/news/brand/83.jpg",
      "brandId": "83"
    }, {
      "text": "金龙",
      "img": "http://x.autoimg.cn/m/news/brand/145.jpg",
      "brandId": "145"
    }, {
      "text": "金旅",
      "img": "http://x.autoimg.cn/m/news/brand/175.jpg",
      "brandId": "175"
    }, {
      "text": "九龙",
      "img": "http://x.autoimg.cn/m/news/brand/151.jpg",
      "brandId": "151"
    }, {
      "text": "Jeep",
      "img": "http://x.autoimg.cn/m/news/brand/46.jpg",
      "brandId": "46"
    }]
  }, {
    "letter": "k",
    "data": [{
      "text": "卡尔森",
      "img": "http://x.autoimg.cn/m/news/brand/156.jpg",
      "brandId": "156"
    }, {
      "text": "卡升",
      "img": "http://x.autoimg.cn/m/news/brand/224.jpg",
      "brandId": "224"
    }, {
      "text": "卡威",
      "img": "http://x.autoimg.cn/m/news/brand/199.jpg",
      "brandId": "199"
    }, {
      "text": "开瑞",
      "img": "http://x.autoimg.cn/m/news/brand/101.jpg",
      "brandId": "101"
    }, {
      "text": "凯迪拉克",
      "img": "http://x.autoimg.cn/m/news/brand/47.jpg",
      "brandId": "47"
    }, {
      "text": "凯翼",
      "img": "http://x.autoimg.cn/m/news/brand/214.jpg",
      "brandId": "214"
    }, {
      "text": "康迪全球鹰",
      "img": "http://x.autoimg.cn/m/news/brand/219.jpg",
      "brandId": "219"
    }, {
      "text": "科尼赛克",
      "img": "http://x.autoimg.cn/m/news/brand/100.jpg",
      "brandId": "100"
    }, {
      "text": "克莱斯勒",
      "img": "http://x.autoimg.cn/m/news/brand/9.jpg",
      "brandId": "9"
    }, {
      "text": "KTM",
      "img": "http://x.autoimg.cn/m/news/brand/109.jpg",
      "brandId": "109"
    }]
  }, {
    "letter": "l",
    "data": [{
      "text": "兰博基尼",
      "img": "http://x.autoimg.cn/m/news/brand/48.jpg",
      "brandId": "48"
    }, {
      "text": "劳伦士",
      "img": "http://x.autoimg.cn/m/news/brand/118.jpg",
      "brandId": "118"
    }, {
      "text": "劳斯莱斯",
      "img": "http://x.autoimg.cn/m/news/brand/54.jpg",
      "brandId": "54"
    }, {
      "text": "雷丁",
      "img": "http://x.autoimg.cn/m/news/brand/215.jpg",
      "brandId": "215"
    }, {
      "text": "雷克萨斯",
      "img": "http://x.autoimg.cn/m/news/brand/52.jpg",
      "brandId": "52"
    }, {
      "text": "雷诺",
      "img": "http://x.autoimg.cn/m/news/brand/10.jpg",
      "brandId": "10"
    }, {
      "text": "理念",
      "img": "http://x.autoimg.cn/m/news/brand/124.jpg",
      "brandId": "124"
    }, {
      "text": "力帆汽车",
      "img": "http://x.autoimg.cn/m/news/brand/80.jpg",
      "brandId": "80"
    }, {
      "text": "莲花汽车",
      "img": "http://x.autoimg.cn/m/news/brand/89.jpg",
      "brandId": "89"
    }, {
      "text": "猎豹汽车",
      "img": "http://x.autoimg.cn/m/news/brand/78.jpg",
      "brandId": "78"
    }, {
      "text": "林肯",
      "img": "http://x.autoimg.cn/m/news/brand/51.jpg",
      "brandId": "51"
    }, {
      "text": "LOCAL MOTORS",
      "img": "http://x.autoimg.cn/m/news/brand/241.jpg",
      "brandId": "241"
    }]
  }, {
    "letter": "m",
    "data": [{
      "text": "铃木",
      "img": "http://x.autoimg.cn/m/news/brand/53.jpg",
      "brandId": "53"
    }, {
      "text": "陆地方舟",
      "img": "http://x.autoimg.cn/m/news/brand/204.jpg",
      "brandId": "204"
    }, {
      "text": "陆风",
      "img": "http://x.autoimg.cn/m/news/brand/88.jpg",
      "brandId": "88"
    }, {
      "text": "路虎",
      "img": "http://x.autoimg.cn/m/news/brand/49.jpg",
      "brandId": "49"
    }, {
      "text": "路特斯",
      "img": "http://x.autoimg.cn/m/news/brand/50.jpg",
      "brandId": "50"
    }, {
      "text": "马自达",
      "img": "http://x.autoimg.cn/m/news/brand/58.jpg",
      "brandId": "58"
    }, {
      "text": "玛莎拉蒂",
      "img": "http://x.autoimg.cn/m/news/brand/57.jpg",
      "brandId": "57"
    }, {
      "text": "迈巴赫",
      "img": "http://x.autoimg.cn/m/news/brand/55.jpg",
      "brandId": "55"
    }, {
      "text": "迈凯伦",
      "img": "http://x.autoimg.cn/m/news/brand/129.jpg",
      "brandId": "129"
    }, {
      "text": "摩根",
      "img": "http://x.autoimg.cn/m/news/brand/168.jpg",
      "brandId": "168"
    }, {
      "text": "MG",
      "img": "http://x.autoimg.cn/m/news/brand/20.jpg",
      "brandId": "20"
    }, {
      "text": "MINI",
      "img": "http://x.autoimg.cn/m/news/brand/56.jpg",
      "brandId": "56"
    }]
  }, {
    "letter": "n",
    "data": [{
      "text": "纳智捷",
      "img": "http://x.autoimg.cn/m/news/brand/130.jpg",
      "brandId": "130"
    }, {
      "text": "南京金龙",
      "img": "http://x.autoimg.cn/m/news/brand/213.jpg",
      "brandId": "213"
    }]
  }, {
    "letter": "o",
    "data": [{
      "text": "讴歌",
      "img": "http://x.autoimg.cn/m/news/brand/60.jpg",
      "brandId": "60"
    }, {
      "text": "欧宝",
      "img": "http://x.autoimg.cn/m/news/brand/59.jpg",
      "brandId": "59"
    }, {
      "text": "欧朗",
      "img": "http://x.autoimg.cn/m/news/brand/146.jpg",
      "brandId": "146"
    }]
  }, {
    "letter": "p",
    "data": [{
      "text": "帕加尼",
      "img": "http://x.autoimg.cn/m/news/brand/61.jpg",
      "brandId": "61"
    }]
  }, {
    "letter": "q",
    "data": [{
      "text": "奇瑞",
      "img": "http://x.autoimg.cn/m/news/brand/26.jpg",
      "brandId": "26"
    }, {
      "text": "启辰",
      "img": "http://x.autoimg.cn/m/news/brand/122.jpg",
      "brandId": "122"
    }, {
      "text": "起亚",
      "img": "http://x.autoimg.cn/m/news/brand/62.jpg",
      "brandId": "62"
    }, {
      "text": "前途",
      "img": "http://x.autoimg.cn/m/news/brand/235.jpg",
      "brandId": "235"
    }]
  }, {
    "letter": "s",
    "data": [{
      "text": "日产",
      "img": "http://x.autoimg.cn/m/news/brand/63.jpg",
      "brandId": "63"
    }, {
      "text": "荣威",
      "img": "http://x.autoimg.cn/m/news/brand/19.jpg",
      "brandId": "19"
    }, {
      "text": "如虎",
      "img": "http://x.autoimg.cn/m/news/brand/174.jpg",
      "brandId": "174"
    }, {
      "text": "瑞麒",
      "img": "http://x.autoimg.cn/m/news/brand/103.jpg",
      "brandId": "103"
    }, {
      "text": "赛麟",
      "img": "http://x.autoimg.cn/m/news/brand/205.jpg",
      "brandId": "205"
    }, {
      "text": "三菱",
      "img": "http://x.autoimg.cn/m/news/brand/68.jpg",
      "brandId": "68"
    }, {
      "text": "陕汽通家",
      "img": "http://x.autoimg.cn/m/news/brand/149.jpg",
      "brandId": "149"
    }, {
      "text": "上汽大通",
      "img": "http://x.autoimg.cn/m/news/brand/155.jpg",
      "brandId": "155"
    }, {
      "text": "世爵",
      "img": "http://x.autoimg.cn/m/news/brand/66.jpg",
      "brandId": "66"
    }, {
      "text": "双环",
      "img": "http://x.autoimg.cn/m/news/brand/90.jpg",
      "brandId": "90"
    }, {
      "text": "双龙",
      "img": "http://x.autoimg.cn/m/news/brand/69.jpg",
      "brandId": "69"
    }, {
      "text": "思铭",
      "img": "http://x.autoimg.cn/m/news/brand/162.jpg",
      "brandId": "162"
    }, {
      "text": "斯巴鲁",
      "img": "http://x.autoimg.cn/m/news/brand/65.jpg",
      "brandId": "65"
    }, {
      "text": "斯达泰克",
      "img": "http://x.autoimg.cn/m/news/brand/238.jpg",
      "brandId": "238"
    }, {
      "text": "斯柯达",
      "img": "http://x.autoimg.cn/m/news/brand/67.jpg",
      "brandId": "67"
    }, {
      "text": "斯威汽车",
      "img": "http://x.autoimg.cn/m/news/brand/269.jpg",
      "brandId": "269"
    }, {
      "text": "smart",
      "img": "http://x.autoimg.cn/m/news/brand/45.jpg",
      "brandId": "45"
    }]
  }, {
    "letter": "t",
    "data": [{
      "text": "泰卡特",
      "img": "http://x.autoimg.cn/m/news/brand/202.jpg",
      "brandId": "202"
    }, {
      "text": "特斯拉",
      "img": "http://x.autoimg.cn/m/news/brand/133.jpg",
      "brandId": "133"
    }, {
      "text": "腾势",
      "img": "http://x.autoimg.cn/m/news/brand/161.jpg",
      "brandId": "161"
    }]
  }, {
    "letter": "w",
    "data": [{
      "text": "威麟",
      "img": "http://x.autoimg.cn/m/news/brand/102.jpg",
      "brandId": "102"
    }, {
      "text": "威兹曼",
      "img": "http://x.autoimg.cn/m/news/brand/99.jpg",
      "brandId": "99"
    }, {
      "text": "潍柴英致",
      "img": "http://x.autoimg.cn/m/news/brand/192.jpg",
      "brandId": "192"
    }, {
      "text": "沃尔沃",
      "img": "http://x.autoimg.cn/m/news/brand/70.jpg",
      "brandId": "70"
    }, {
      "text": "五菱汽车",
      "img": "http://x.autoimg.cn/m/news/brand/114.jpg",
      "brandId": "114"
    }, {
      "text": "五十铃",
      "img": "http://x.autoimg.cn/m/news/brand/167.jpg",
      "brandId": "167"
    }]
  }, {
    "letter": "x",
    "data": [{
      "text": "西雅特",
      "img": "http://x.autoimg.cn/m/news/brand/98.jpg",
      "brandId": "98"
    }, {
      "text": "现代",
      "img": "http://x.autoimg.cn/m/news/brand/12.jpg",
      "brandId": "12"
    }, {
      "text": "新凯",
      "img": "http://x.autoimg.cn/m/news/brand/185.jpg",
      "brandId": "185"
    }, {
      "text": "雪佛兰",
      "img": "http://x.autoimg.cn/m/news/brand/71.jpg",
      "brandId": "71"
    }, {
      "text": "雪铁龙",
      "img": "http://x.autoimg.cn/m/news/brand/72.jpg",
      "brandId": "72"
    }]
  }, {
    "letter": "y",
    "data": [{
      "text": "野马汽车",
      "img": "http://x.autoimg.cn/m/news/brand/111.jpg",
      "brandId": "111"
    }, {
      "text": "一汽",
      "img": "http://x.autoimg.cn/m/news/brand/110.jpg",
      "brandId": "110"
    }, {
      "text": "依维柯",
      "img": "http://x.autoimg.cn/m/news/brand/144.jpg",
      "brandId": "144"
    }, {
      "text": "英菲尼迪",
      "img": "http://x.autoimg.cn/m/news/brand/73.jpg",
      "brandId": "73"
    }, {
      "text": "永源",
      "img": "http://x.autoimg.cn/m/news/brand/93.jpg",
      "brandId": "93"
    }, {
      "text": "驭胜",
      "img": "http://x.autoimg.cn/m/news/brand/263.jpg",
      "brandId": "263"
    }]
  }, {
    "letter": "z",
    "data": [{
      "text": "长安",
      "img": "http://x.autoimg.cn/m/news/brand/76.jpg",
      "brandId": "76"
    }, {
      "text": "长安商用",
      "img": "http://x.autoimg.cn/m/news/brand/163.jpg",
      "brandId": "163"
    }, {
      "text": "长城",
      "img": "http://x.autoimg.cn/m/news/brand/77.jpg",
      "brandId": "77"
    }, {
      "text": "之诺",
      "img": "http://x.autoimg.cn/m/news/brand/182.jpg",
      "brandId": "182"
    }, {
      "text": "知豆",
      "img": "http://x.autoimg.cn/m/news/brand/206.jpg",
      "brandId": "206"
    }, {
      "text": "中华",
      "img": "http://x.autoimg.cn/m/news/brand/22.jpg",
      "brandId": "22"
    }, {
      "text": "中兴",
      "img": "http://x.autoimg.cn/m/news/brand/74.jpg",
      "brandId": "74"
    }, {
      "text": "众泰",
      "img": "http://x.autoimg.cn/m/news/brand/94.jpg",
      "brandId": "94"
    }]
  }
];
  return{
    brandData:brandData,
  }
}) 
